apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-deploy
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: keycloak
    repoURL: https://github.com/ysoni-redhat/rhdh-keycloak-argocd.git
    targetRevision: phase-1-work
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - StructuredDiff=true        
  ignoreDifferences:
    - group: k8s.keycloak.org
      kind: Keycloak
      jsonPointers:
        - /status        
